import type { PermissionSet, UserRole } from '../types'

export const ROLE_PERMISSIONS: Record<UserRole, PermissionSet> = {
  SUPER_ADMIN: {
    canViewDashboard: true,
    canManageCustomers: true,
    canCreateCustomer: true,
    canEditCustomer: true,
    canDeleteCustomer: true,
    canManageChits: true,
    canManageCollections: true,
    canCollectPayment: true,
    canViewReports: true,
    canManageAuctions: true,
    canManageUsers: true,
    canManageOffices: true,
    canManageKyc: true,
    canViewSettings: true,
    canAccessAuditLogs: true,
  },
  ADMIN: {
    canViewDashboard: true,
    canManageCustomers: true,
    canCreateCustomer: true,
    canEditCustomer: true,
    canDeleteCustomer: true,
    canManageChits: true,
    canManageCollections: true,
    canCollectPayment: true,
    canViewReports: true,
    canManageAuctions: true,
    canManageUsers: true,
    canManageOffices: true,
    canManageKyc: true,
    canViewSettings: true,
    canAccessAuditLogs: true,
  },
  OFFICE_MANAGER: {
    canViewDashboard: true,
    canManageCustomers: true,
    canCreateCustomer: true,
    canEditCustomer: true,
    canDeleteCustomer: false,
    canManageChits: true,
    canManageCollections: true,
    canCollectPayment: true,
    canViewReports: true,
    canManageAuctions: false,
    canManageUsers: false,
    canManageOffices: false,
    canManageKyc: true,
    canViewSettings: true,
    canAccessAuditLogs: true,
  },
  OFFICE_STAFF: {
    canViewDashboard: true,
    canManageCustomers: true,
    canCreateCustomer: true,
    canEditCustomer: true,
    canDeleteCustomer: false,
    canManageChits: false,
    canManageCollections: true,
    canCollectPayment: true,
    canViewReports: false,
    canManageAuctions: false,
    canManageUsers: false,
    canManageOffices: false,
    canManageKyc: false,
    canViewSettings: false,
    canAccessAuditLogs: false,
  },
  ACCOUNTANT: {
    canViewDashboard: true,
    canManageCustomers: false,
    canCreateCustomer: false,
    canEditCustomer: false,
    canDeleteCustomer: false,
    canManageChits: false,
    canManageCollections: true,
    canCollectPayment: false,
    canViewReports: true,
    canManageAuctions: false,
    canManageUsers: false,
    canManageOffices: false,
    canManageKyc: true,
    canViewSettings: true,
    canAccessAuditLogs: true,
  },
  COLLECTION_AGENT: {
    canViewDashboard: true,
    canManageCustomers: true,
    canCreateCustomer: false,
    canEditCustomer: false,
    canDeleteCustomer: false,
    canManageChits: false,
    canManageCollections: true,
    canCollectPayment: true,
    canViewReports: false,
    canManageAuctions: false,
    canManageUsers: false,
    canManageOffices: false,
    canManageKyc: false,
    canViewSettings: false,
    canAccessAuditLogs: false,
  },
}

export const hasPermission = (
  userRole: UserRole,
  permission: keyof PermissionSet,
): boolean => ROLE_PERMISSIONS[userRole]?.[permission] ?? false

export const canAccessRoute = (userRole: UserRole, route: string): boolean => {
  const routeMap: Record<string, keyof PermissionSet> = {
    '/dashboard': 'canViewDashboard',
    '/customers': 'canManageCustomers',
    '/chit-schemes': 'canManageChits',
    '/chit-groups': 'canManageChits',
    '/members': 'canManageCustomers',
    '/installments': 'canManageCollections',
    '/payments': 'canCollectPayment',
    '/auctions': 'canManageAuctions',
    '/reports': 'canViewReports',
    '/offices': 'canManageOffices',
    '/staff': 'canManageUsers',
    '/agents': 'canManageCollections',
    '/notifications': 'canViewDashboard',
    '/audit-logs': 'canAccessAuditLogs',
    '/settings': 'canViewSettings',
  }

  const permission = routeMap[route]
  return permission ? hasPermission(userRole, permission) : true
}
